#data:
data_dir: "D:/Data"
dataset: 'limestone'
n_classes: 2
is_not_ready: true
standardization: true
std_mean_path: null

#model:
ckpt: "C:/tomograph4/Scripts/analytics_2/checkpoints/dinov2_vit_base_14.pth"
num_codebook: 2048
reduced_dim: 90
projection_dim: 2048
run_name: 'train_dinov2'
dim: null 
num_queries: null
device: null

#training:
distributed: false
load_segment: false
load_cluster: false
mediator_epoch: 1
front_epoch: 2
fine_tune_epoch: 5
batch_size: 16
learning_rate: 1.0e-3
num_workers: 2
thresh_pos: 0.3
thresh_neg: 0.1
temp: 0.1
grid: true
degree_of_sampling: 2

#processing:
patch_size: 320
train_resolution: 320
patches_shape: null
overlap_fraction: 0.2
max_images: 50

#hardware:
gpu: '0'
port: '12355'